// Generated by gencpp from file detector_ros/ShapeDetections.msg
// DO NOT EDIT!


#ifndef DETECTOR_ROS_MESSAGE_SHAPEDETECTIONS_H
#define DETECTOR_ROS_MESSAGE_SHAPEDETECTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <detector_ros/ShapeDetection.h>

namespace detector_ros
{
template <class ContainerAllocator>
struct ShapeDetections_
{
  typedef ShapeDetections_<ContainerAllocator> Type;

  ShapeDetections_()
    : header()
    , detections()  {
    }
  ShapeDetections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::detector_ros::ShapeDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::detector_ros::ShapeDetection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::detector_ros::ShapeDetections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detector_ros::ShapeDetections_<ContainerAllocator> const> ConstPtr;

}; // struct ShapeDetections_

typedef ::detector_ros::ShapeDetections_<std::allocator<void> > ShapeDetections;

typedef boost::shared_ptr< ::detector_ros::ShapeDetections > ShapeDetectionsPtr;
typedef boost::shared_ptr< ::detector_ros::ShapeDetections const> ShapeDetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detector_ros::ShapeDetections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detector_ros::ShapeDetections_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detector_ros::ShapeDetections_<ContainerAllocator1> & lhs, const ::detector_ros::ShapeDetections_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detector_ros::ShapeDetections_<ContainerAllocator1> & lhs, const ::detector_ros::ShapeDetections_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detector_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detector_ros::ShapeDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detector_ros::ShapeDetections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_ros::ShapeDetections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_ros::ShapeDetections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_ros::ShapeDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_ros::ShapeDetections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detector_ros::ShapeDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c04579eff31e78139542754e76efe173";
  }

  static const char* value(const ::detector_ros::ShapeDetections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc04579eff31e7813ULL;
  static const uint64_t static_value2 = 0x9542754e76efe173ULL;
};

template<class ContainerAllocator>
struct DataType< ::detector_ros::ShapeDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detector_ros/ShapeDetections";
  }

  static const char* value(const ::detector_ros::ShapeDetections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detector_ros::ShapeDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"detector_ros/ShapeDetection[] detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: detector_ros/ShapeDetection\n"
"string shape\n"
"string color\n"
"int32 cx\n"
"int32 cy\n"
"float32 area\n"
;
  }

  static const char* value(const ::detector_ros::ShapeDetections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detector_ros::ShapeDetections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShapeDetections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detector_ros::ShapeDetections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detector_ros::ShapeDetections_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detections: ";
    if (v.detections.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::detector_ros::ShapeDetection_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.detections[i]);
    }
    if (v.detections.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTOR_ROS_MESSAGE_SHAPEDETECTIONS_H
